name: Publish Docker image
on:
  push:
    branches:
    - aws
    - public-ecr
jobs:
  aws-public-ecr:
    strategy:
      matrix:
        include:
        - terraform_version: 1.3.3
          terragrunt_version: 0.39.2
          tag: kinetic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: eu-west-3
    - name: Login to Amazon ECR Public
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: public
    - run: yarn install --frozen-lockfile
    - run: sh ./scripts/download.sh files/terraform_linux_amd64.zip https://releases.hashicorp.com/terraform/${{ matrix.terraform_version }}/terraform_${{ matrix.terraform_version }}_linux_amd64.zip
    - run: sh ./scripts/download.sh files/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v${{ matrix.terragrunt_version }}/terragrunt_linux_amd64
    - run: sh ./scripts/download.sh files/awscli.zip https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    - name: Build, tag, and push docker image to Amazon ECR Public
      env:
        REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
        REGISTRY_ALIAS: k2s5i1w6
        REPOSITORY: ubuntu-devops
        IMAGE_TAG: ${{ matrix.tag }}
      run: |
        docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
