name: Publish Docker image
on:
  push:
    branches:
    - main
jobs:
  build:
    strategy:
      matrix:
        include:
        - terraform_version: 1.3.3
          terragrunt_version: 0.39.2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: yarn install --frozen-lockfile
    - run: sh ./scripts/download.sh files/terraform_linux_amd64.zip https://releases.hashicorp.com/terraform/${{ matrix.terraform_version }}/terraform_${{ matrix.terraform_version }}_linux_amd64.zip
    - run: sh ./scripts/download.sh files/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v${{ matrix.terragrunt_version }}/terragrunt_linux_amd64
    - run: sh ./scripts/download.sh files/awscli.zip https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        build-args: |
          TERRAFORM_VERSION=${{ matrix.terraform_version }}
          TERRAGRUNT_VERSION=${{ matrix.terragrunt_version }}
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ubuntu-devops:kinetic
